"""store package — encrypted config persistence, query logging, client registry, user management."""
from store.db import init_db, get_db
from store.crypto import encrypt, decrypt, decrypt_json, mask
from store.config_store import (
    save_metric, list_metrics, get_metric, update_metric,
    delete_metric, deprecate_metric, match_metric, list_metric_formula_context,
    validate_metric_refs, increment_metric_usage,
    save_validated_example, get_validated_examples,
    harvest_successful_queries,
    load_schema_tables,
    set_system, get_system, get_all_system, SYSTEM_KEYS,
    LLM_COST_RATES, calculate_cost, get_all_pricing, save_pricing,
    log_kb_egress, list_kb_egress, get_kb_egress_summary, update_egress_masking,
    confirm_entity_property, reject_entity_property,
    save_entity, list_entities, get_entity, delete_entity, prune_entity_graph_to_tables,
    save_relationship, list_relationships, delete_relationship,
    get_relationship, upsert_relationship_by_pair, upsert_relationship_by_identity,
    update_relationship_validation,
    save_entity_property, list_entity_properties, list_all_entity_properties, get_full_graph,
    count_pending_graph_reviews, count_pending_structural_graph_reviews,
    flag_relationships_needing_review, clear_relationship_review_flag,
    save_graph_version, list_graph_versions, get_graph_version,
    replace_graph_from_snapshot,
    save_platform, get_platform, list_platforms, delete_platform,
    PLATFORM_FIELDS, PLATFORM_LABELS,
    save_db_config, get_db_config, list_db_configs, delete_db_config,
    DB_REQUIRED_FIELDS, DB_DIALECT, DB_LABEL,
    upsert_client, get_client, get_client_state, list_clients, delete_client,
    update_client_state, update_client_meta, get_monthly_query_count,
    get_client_by_teams_tenant_id,
    get_monthly_token_usage, get_monthly_token_status,
    log_query, get_query_stats, get_recent_queries, get_monthly_breakdown,
    search_recent_queries_referencing,
    get_suggestions,
    log_llm_call, get_recent_llm_calls, purge_old_llm_calls,
    get_llm_trust_summary, RESULT_LLM_COMPONENTS,
)
from store.user_store import (
    create_group, list_groups, get_group, update_group, delete_group,
    set_group_tables, get_group_tables,
    create_user, get_user, get_user_by_email, get_user_by_zoom_id, get_user_by_platform_id,
    list_users, update_user, change_password, reset_user_password,
    link_zoom_user, verify_password, delete_user,
    set_user_extra_tables, get_user_extra_tables, get_allowed_tables,
    create_registration_token, consume_registration_token,
    upsert_pending_user, list_pending_users, get_pending_user_count,
    approve_pending_user, reject_pending_user, get_pending_user,
    pin_chart, list_pinned_charts, delete_pinned_chart,
    update_pinned_chart_title, update_pinned_chart, update_chart_refreshed,
    update_pinned_chart_layouts,
    generate_temp_password,
)
from store.semantic_store import (
    save_term, get_term, list_terms, delete_term, set_term_active,
    match_terms_in_question, find_ambiguous_term,
    filter_metric_colliding_terms,
    build_term_injection, build_term_injection_from_choice,
    extract_terms_from_kb, glossary_stats,
)
from store.semantic_feedback import (
    save_semantic_field_feedback, list_semantic_field_feedback,
    count_semantic_field_feedback, review_semantic_field_feedback,
    list_recent_reviewed_semantic_feedback,
    semantic_feedback_maps, semantic_feedback_pending_summary,
)
from store.date_context_store import (
    save_metric_date_context, list_metric_date_contexts,
    get_metric_date_context, delete_metric_date_context,
)
from store.trace_store import (
    create_answer_trace, update_answer_trace, log_answer_trace_step,
    finish_answer_trace, kb_chunk_refs, get_answer_trace, list_answer_traces,
    get_kb_doc_quality,
    get_answer_trace_by_question_id,
    store_protected_result_rows,
    find_reusable_validated_sql_plan,
)
from store.eval_store import (
    save_eval_run, save_eval_case_result, list_eval_runs,
    get_eval_run, latest_eval_run, previous_eval_run, latest_regressed_run,
)
from store.compliance_store import (
    get_compliance_profile, save_compliance_profile,
    create_policy_version, activate_policy_version, list_policy_versions,
    list_classifications, get_classification_map, save_classification,
    list_policy_rules, replace_policy_rules, list_row_policies, replace_row_policies,
    list_purposes, replace_purposes,
    provider_agreement_valid, save_provider_agreement, list_provider_agreements,
    save_user_attestation, revoke_user_attestation,
    user_attestation_valid, list_user_attestations,
    log_policy_decision, list_decisions, log_export_event,
    get_policy_decision_counts,
    create_break_glass_grant, get_active_break_glass_grant,
    get_active_break_glass_for_user,
    save_assessment, get_latest_assessment,
)
from store.semantic_compile_store import (
    get_semantic_compiler_state, set_semantic_compiler_mode,
    create_semantic_compile_run, finish_semantic_compile_run,
    save_semantic_contract_version, publish_semantic_contract_version,
    set_semantic_draft_version, save_semantic_conflicts,
    reconcile_semantic_conflicts, list_semantic_conflicts,
    get_semantic_compiler_summary, get_semantic_conflict,
    resolve_semantic_conflict, list_semantic_contract_versions,
    get_semantic_contract_version,
)

__all__ = [
    "init_db","get_db","encrypt","decrypt","decrypt_json","mask",
    "set_system","get_system","get_all_system","SYSTEM_KEYS",
    "LLM_COST_RATES","calculate_cost","get_all_pricing","save_pricing",
    "log_kb_egress","list_kb_egress","get_kb_egress_summary","update_egress_masking",
    "confirm_entity_property","reject_entity_property",
    "save_entity","list_entities","get_entity","delete_entity","prune_entity_graph_to_tables",
    "save_relationship","list_relationships","delete_relationship",
    "get_relationship","upsert_relationship_by_pair","upsert_relationship_by_identity",
    "update_relationship_validation",
    "save_entity_property","list_entity_properties","list_all_entity_properties","get_full_graph",
    "count_pending_graph_reviews","count_pending_structural_graph_reviews",
    "flag_relationships_needing_review","clear_relationship_review_flag",
    "save_graph_version","list_graph_versions","get_graph_version",
    "replace_graph_from_snapshot",
    "save_metric","list_metrics","get_metric","update_metric",
    "delete_metric","deprecate_metric","match_metric","list_metric_formula_context",
    "increment_metric_usage",
    "save_platform","get_platform","list_platforms","delete_platform",
    "PLATFORM_FIELDS","PLATFORM_LABELS",
    "save_db_config","get_db_config","list_db_configs","delete_db_config",
    "DB_REQUIRED_FIELDS","DB_DIALECT","DB_LABEL",
    "upsert_client","get_client","get_client_state","list_clients","delete_client",
    "update_client_state","update_client_meta","get_monthly_query_count",
    "get_client_by_teams_tenant_id",
    "get_monthly_token_usage","get_monthly_token_status",
    "log_query","get_query_stats","get_recent_queries","get_monthly_breakdown",
    "search_recent_queries_referencing",
    "get_suggestions",
    "log_llm_call","get_recent_llm_calls","purge_old_llm_calls",
    "get_llm_trust_summary","RESULT_LLM_COMPONENTS",
    "create_group","list_groups","get_group","update_group","delete_group",
    "set_group_tables","get_group_tables",
    "create_user","get_user","get_user_by_email","get_user_by_zoom_id","get_user_by_platform_id",
    "list_users","update_user","change_password","reset_user_password",
    "link_zoom_user","verify_password","delete_user",
    "set_user_extra_tables","get_user_extra_tables","get_allowed_tables",
    "create_registration_token","consume_registration_token",
    "upsert_pending_user","list_pending_users","get_pending_user_count",
    "approve_pending_user","reject_pending_user","get_pending_user",
    "pin_chart","list_pinned_charts","delete_pinned_chart",
    "update_pinned_chart_title","update_pinned_chart","update_chart_refreshed",
    "update_pinned_chart_layouts",
    "generate_temp_password",
    # Business semantic layer
    "save_term","get_term","list_terms","delete_term","set_term_active",
    "match_terms_in_question","find_ambiguous_term",
    "filter_metric_colliding_terms",
    "build_term_injection","build_term_injection_from_choice",
    "extract_terms_from_kb","glossary_stats",
    "save_semantic_field_feedback","list_semantic_field_feedback",
    "count_semantic_field_feedback","review_semantic_field_feedback",
    "list_recent_reviewed_semantic_feedback",
    "semantic_feedback_maps","semantic_feedback_pending_summary",
    "save_metric_date_context","list_metric_date_contexts",
    "get_metric_date_context","delete_metric_date_context",
    "create_answer_trace","update_answer_trace","log_answer_trace_step",
    "finish_answer_trace","kb_chunk_refs","get_answer_trace","list_answer_traces",
    "get_kb_doc_quality",
    "get_answer_trace_by_question_id",
    "store_protected_result_rows",
    "find_reusable_validated_sql_plan",
    "save_eval_run","save_eval_case_result","list_eval_runs",
    "get_eval_run","latest_eval_run","previous_eval_run","latest_regressed_run",
    "get_compliance_profile","save_compliance_profile",
    "create_policy_version","activate_policy_version","list_policy_versions",
    "list_classifications","get_classification_map","save_classification",
    "list_policy_rules","replace_policy_rules","list_row_policies","replace_row_policies",
    "list_purposes","replace_purposes",
    "provider_agreement_valid","save_provider_agreement","list_provider_agreements",
    "save_user_attestation","revoke_user_attestation",
    "user_attestation_valid","list_user_attestations",
    "log_policy_decision","list_decisions","log_export_event",
    "get_policy_decision_counts",
    "create_break_glass_grant","get_active_break_glass_grant",
    "get_active_break_glass_for_user",
    "save_assessment","get_latest_assessment",
    "get_semantic_compiler_state","set_semantic_compiler_mode",
    "create_semantic_compile_run","finish_semantic_compile_run",
    "save_semantic_contract_version","publish_semantic_contract_version",
    "set_semantic_draft_version","save_semantic_conflicts",
    "reconcile_semantic_conflicts","list_semantic_conflicts",
    "get_semantic_compiler_summary","get_semantic_conflict",
    "resolve_semantic_conflict","list_semantic_contract_versions",
    "get_semantic_contract_version",
]
