"""store package — encrypted config persistence, query logging, client registry, user management."""
from store.db import init_db, get_db
from store.crypto import encrypt, decrypt, decrypt_json, mask
from store.config_store import (
    save_metric, list_metrics, get_metric, update_metric,
    delete_metric, match_metric, list_metric_formula_context,
    save_validated_example, get_validated_examples,
    harvest_successful_queries,
    load_schema_tables,
    set_system, get_system, get_all_system, SYSTEM_KEYS,
    LLM_COST_RATES, calculate_cost, get_all_pricing, save_pricing,
    log_kb_egress, list_kb_egress, get_kb_egress_summary, update_egress_masking,
    confirm_entity_property,
    save_entity, list_entities, get_entity, delete_entity,
    save_relationship, list_relationships, delete_relationship,
    save_entity_property, list_entity_properties, get_full_graph,
    save_platform, get_platform, list_platforms, delete_platform,
    PLATFORM_FIELDS, PLATFORM_LABELS,
    save_db_config, get_db_config, list_db_configs, delete_db_config,
    DB_REQUIRED_FIELDS, DB_DIALECT, DB_LABEL,
    upsert_client, get_client, get_client_state, list_clients, delete_client,
    update_client_state, update_client_meta, get_monthly_query_count,
    get_monthly_token_usage, get_monthly_token_status,
    log_query, get_query_stats, get_recent_queries, get_monthly_breakdown,
    log_llm_call, get_recent_llm_calls, purge_old_llm_calls,
)
from store.user_store import (
    create_group, list_groups, get_group, update_group, delete_group,
    set_group_tables, get_group_tables,
    create_user, get_user, get_user_by_email, get_user_by_zoom_id,
    list_users, update_user, change_password, reset_user_password,
    link_zoom_user, verify_password, delete_user,
    set_user_extra_tables, get_user_extra_tables, get_allowed_tables,
    create_registration_token, consume_registration_token,
    pin_chart, list_pinned_charts, delete_pinned_chart,
    update_pinned_chart_title, update_chart_refreshed,
    generate_temp_password,
)
from store.semantic_store import (
    save_term, get_term, list_terms, delete_term, set_term_active,
    match_terms_in_question, find_ambiguous_term,
    build_term_injection, build_term_injection_from_choice,
    extract_terms_from_kb, glossary_stats,
)
from store.semantic_feedback import (
    save_semantic_field_feedback, list_semantic_field_feedback,
    count_semantic_field_feedback, review_semantic_field_feedback,
    list_recent_reviewed_semantic_feedback,
    semantic_feedback_maps, semantic_feedback_pending_summary,
)

__all__ = [
    "init_db","get_db","encrypt","decrypt","decrypt_json","mask",
    "set_system","get_system","get_all_system","SYSTEM_KEYS",
    "LLM_COST_RATES","calculate_cost","get_all_pricing","save_pricing",
    "log_kb_egress","list_kb_egress","get_kb_egress_summary","update_egress_masking",
    "confirm_entity_property",
    "save_entity","list_entities","get_entity","delete_entity",
    "save_relationship","list_relationships","delete_relationship",
    "save_entity_property","list_entity_properties","get_full_graph",
    "save_metric","list_metrics","get_metric","update_metric",
    "delete_metric","match_metric","list_metric_formula_context",
    "save_platform","get_platform","list_platforms","delete_platform",
    "PLATFORM_FIELDS","PLATFORM_LABELS",
    "save_db_config","get_db_config","list_db_configs","delete_db_config",
    "DB_REQUIRED_FIELDS","DB_DIALECT","DB_LABEL",
    "upsert_client","get_client","get_client_state","list_clients","delete_client",
    "update_client_state","update_client_meta","get_monthly_query_count",
    "get_monthly_token_usage","get_monthly_token_status",
    "log_query","get_query_stats","get_recent_queries","get_monthly_breakdown",
    "log_llm_call","get_recent_llm_calls","purge_old_llm_calls",
    "create_group","list_groups","get_group","update_group","delete_group",
    "set_group_tables","get_group_tables",
    "create_user","get_user","get_user_by_email","get_user_by_zoom_id",
    "list_users","update_user","change_password","reset_user_password",
    "link_zoom_user","verify_password","delete_user",
    "set_user_extra_tables","get_user_extra_tables","get_allowed_tables",
    "create_registration_token","consume_registration_token",
    "pin_chart","list_pinned_charts","delete_pinned_chart",
    "update_pinned_chart_title","update_chart_refreshed",
    "generate_temp_password",
    # Business semantic layer
    "save_term","get_term","list_terms","delete_term","set_term_active",
    "match_terms_in_question","find_ambiguous_term",
    "build_term_injection","build_term_injection_from_choice",
    "extract_terms_from_kb","glossary_stats",
    "save_semantic_field_feedback","list_semantic_field_feedback",
    "count_semantic_field_feedback","review_semantic_field_feedback",
    "list_recent_reviewed_semantic_feedback",
    "semantic_feedback_maps","semantic_feedback_pending_summary",
]
