"""Running read-only SQL for core2.

Everything core2 sends to a warehouse goes through a :class:`Warehouse`. Two
implementations exist: :class:`DuckDBWarehouse` for the synthetic domains and
local copies, and the QueryBot connection runner (added with the integration)
that uses the workspace's configured database.

Bootstrap SQL is generated by code, never by a model, and :func:`assert_read_only`
refuses anything that is not a single SELECT before it is sent anywhere.
"""

from __future__ import annotations

import threading
import time
from dataclasses import dataclass, field
from typing import Any, Protocol

import sqlglot
from sqlglot import exp


@dataclass
class QueryResult:
    columns: list[str]
    rows: list[tuple[Any, ...]]
    truncated: bool = False
    elapsed_ms: float = 0.0


class ReadOnlyViolation(ValueError):
    pass


_WRITES = (exp.Insert, exp.Update, exp.Delete, exp.Merge, exp.Create, exp.Drop, exp.Alter, exp.Command,
           exp.TruncateTable)


def assert_read_only(sql: str, dialect: str) -> None:
    """Refuse anything but one SELECT (with CTEs/unions) in ``dialect``."""
    try:
        statements = [s for s in sqlglot.parse(sql, read=dialect) if s is not None]
    except sqlglot.errors.ParseError as exc:
        raise ReadOnlyViolation(f"unparseable SQL: {exc}") from None
    if len(statements) != 1:
        raise ReadOnlyViolation("exactly one statement is allowed")
    statement = statements[0]
    if not isinstance(statement, (exp.Select, exp.Union, exp.Intersect, exp.Except)):
        raise ReadOnlyViolation(f"only SELECT is allowed, not {type(statement).__name__}")
    for node in statement.walk():
        if isinstance(node, _WRITES) or (isinstance(node, exp.Into)):
            raise ReadOnlyViolation(f"{type(node).__name__} is not allowed")


class Warehouse(Protocol):
    dialect: str      # sqlglot dialect: snowflake | tsql | oracle | duckdb
    db_type: str      # QueryBot database type: snowflake | azure_sql | oracle | duckdb

    def query(self, sql: str, *, max_rows: int | None = None) -> QueryResult: ...


@dataclass
class DuckDBWarehouse:
    """A DuckDB connection (a synthetic domain or a local copy), read-only by contract."""

    connection: Any
    database: str = ""
    schema: str = "main"
    dialect: str = "duckdb"
    db_type: str = "duckdb"
    log: list[str] = field(default_factory=list)
    _lock: threading.Lock = field(default_factory=threading.Lock, repr=False)

    def query(self, sql: str, *, max_rows: int | None = None) -> QueryResult:
        assert_read_only(sql, self.dialect)
        start = time.perf_counter()
        with self._lock:
            self.log.append(sql)
            cursor = self.connection.cursor()
            try:
                cursor.execute(sql)
                columns = [d[0] for d in (cursor.description or [])]
                if max_rows is None:
                    rows = cursor.fetchall()
                    truncated = False
                else:
                    rows = cursor.fetchmany(max_rows + 1)
                    truncated = len(rows) > max_rows
                    rows = rows[:max_rows]
            finally:
                cursor.close()
        return QueryResult(columns, [tuple(r) for r in rows], truncated, (time.perf_counter() - start) * 1000)
